blogging/urls.py
from django.urls import path
from blogging.views import PostDetailView, PostListView

urlpatterns = [
    path("", PostListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="blog_detail"),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("", include("polling.urls")),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("", include("polling.urls")),
    path("blogging/", include("blogging.urls")),
    path(
        "login/",
        LoginView.as_view(template_name="login.html", next_page="/"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("accounts/", include("allauth.urls")),  # new
]

polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

django_blog/blogging/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blogging.models import Post


class PostListView(ListView):
    model = Post
    template_name = "blogging/list.html"
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )


class PostDetailView(DetailView):
    model = Post
    template_name = "blogging/detail.html"
    queryset = Post.objects.exclude(published_date__exact=None)

polling/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from polling.models import Poll


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()
        context = {"object": poll}
        return render(request, "polling/detail.html", context)

blogging/templates/blogging/detail.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ post }}</h1>
    <p class="byline">
        Posted by {{ post.author.username }}
    </p>
<div class="post-body">
    {{ post.text }}
</div>
<ul class="categories">
    {% for category in post.categories.all %}
</ul>
{% endfor %}
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}

{% block content %}
    <h1>Recent Posts</h1>
    {% comment %} Here is where the query happens {% endcomment %}
    {% for post in post_list %}
        <div class="post">
            <h2>
                <a href="{% url 'blog_detail' post.pk %}"> {{ post }}</a>
            </h2>
            <p class="byline">
                Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
            </p>
            <div class="post-body">
                {{ post.text }}
            </div>
            <ul class="categories">
                {% for category in post.categories.all %}
                    <li>{{ category }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

django_blog/django_blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
  </head>
  <body>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

django_blog/templates/base.html
{% load socialaccount %}
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}"
  </head>
  <body>
    <div id="header">
      <ul id="control-bar">
          {% if user.is_authenticated %}
              <li>Hello {{ user.username }} </li>
              {% if user.is_stafe %}
                  <li>
                      <a href="{% url 'admin.index' %}">admin</a>
                  </li>
              {% endif %}
              <li>
                  <form id="frm_logout" method="POST" action="{% url 'logout' %}">
                      {% csrf_token %}
                      <a href="javascript:$('#frm_logout').submit();">logout</a>
                  </form>
              </li>
          {% else %}
          <li>
              <a href="{% url 'account_login' %}">login</a>
          </li>
          <!-- GitHub Login Button -->
          <li>
              <a href="{% provider_login_url 'github' %}" class="github-login">
                  <img src="https://github.com/favicon.ico" alt="GitHub Login"> Login with GitHub
              </a>
          </li>
          {% endif %}
      </ul>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

django_blog/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
    {{ form.as_p}}
    <p><input type="submit" value="Login"></p>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title}}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}